name: llm-uncertainty
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - pytorch
  - transformers
  - uncertainty-toolbox
  - langchain-community
  - langchain-openai
  - langchain-core
  - pip:
      - dotenv
      - accelerate
      - huggingface-hub
  