name: llm-uncertainty
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - transformers
  - huggingface_hub
  - uncertainty-toolbox
  - langchain-community
  - langchain-openai
  - langchain-core
  - pip:
      - dotenv
      - accelerate
      - auto-gptq
      - torch --index-url https://download.pytorch.org/whl/cu124


  