name: llm-uncertainty
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - huggingface_hub
  - uncertainty-toolbox
  - langchain-community
  - langchain-openai
  - langchain-core
  - python-dotenv
  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu128
    - exllama
    - bitsandbytes
    - accelerate
    - transformers>=4.38.0
    - peft>=0.15.0
    - auto-gptq
    - protobuf
    - optimum
  
  

  